image: node:11

cache:
  paths:
  - node_modules/

stages:
  - test

run_tests:
  stage: test
  script:
   - npm install
   - npm install https://github.com/RainBlock/merkle-patricia-tree
   - npm run test
  tags:
    - docker
