image: node:11.11.0

cache:
  paths:
  - node_modules/

stages:
  - test

run_tests:
  stage: test
  script:
   - npm install
   - npm run prepare
   - npm run test
   - node -r ts-node/register src/server.ts -1 50051 &
   - sleep 5
   - node -r ts-node/register src/testClient.ts 50051
  tags:
    - docker
