image: node:11.11.0

cache:
  paths:
  - node_modules/

stages:
  - test

run_tests:
  stage: test
  script:
   - node -v
   - npm -v
   - tsc -v
   - npm install
   - npm run test
  tags:
    - docker
